In [1]:
import numpy as np

In [2]:
def f(x):
    return x * np.sin(3*x) - np.exp(x)

def df(x):
    return np.sin(3*x) + 3*x*np.cos(3*x) - np.exp(x)

In [3]:
x = np.array([-1.6])
for i in range(1000):
    x = np.append(x, x [i] - f(x[i]) / df(x[i]))
    fc = f(x[i])

    if abs(fc) < 1e-6 :
        break

display(x)
display(i+1)
display(x[i])
display(fc)

np.save('A1.npy', x)

array([-1.6       ,  3.19799514,  2.46440244,  1.2035359 ,  0.65020146,
       -0.11692334, -0.66052349, -0.52192654, -0.56655274, -0.57074658,
       -0.57078962, -0.57078962])

11

np.float64(-0.57078961788788)

np.float64(-6.016180886803113e-09)

In [4]:
xl = -0.7
xr = -0.4
xcstore = np.array([])
for j in range(0,1000):
    xc = (xl + xr) / 2
    fc = f(xc)
    if fc > 0 :
        xl = xc
    else :
        xr = xc

    xcstore = np.append(xcstore, xc)
    if abs(fc) < 1e-6 :
        break
    

display(xcstore)
display(j+1)
display(xc)
display(fc)

np.save('A2.npy', xcstore)
np.save('A3.npy', [i+1,j+1])

array([-0.55      , -0.625     , -0.5875    , -0.56875   , -0.578125  ,
       -0.5734375 , -0.57109375, -0.56992188, -0.57050781, -0.57080078,
       -0.5706543 , -0.57072754, -0.57076416, -0.57078247, -0.57079163,
       -0.57078705, -0.57078934])

17

-0.5707893371582031

np.float64(-3.747433618972451e-07)

In [5]:
A = np.array([[1,2],[-1,1]])
B = np.array([[2,0],[0,2]])
C = np.array([[2,0,-3],[0,0,-1]])
D = np.array([[1,2],[2,3],[-1,0]])
x = np.array([1,0])
y = np.array([0,1])
z = np.array([1,2,-1])

np.save('A4.npy', A + B)
np.save('A5.npy', (3*x - 4*y))
np.save('A6.npy', np.dot(A,x))
np.save('A7.npy', np.dot(B, x - y))
np.save('A8.npy', np.dot(D, x))
np.save('A9.npy', np.dot(D, y) + z)
np.save('A10.npy', np.dot(A, B))
np.save('A11.npy', np.dot(B, C))
np.save('A12.npy', np.dot(C, D))

display((np.dot(D,y) +z))

array([ 3,  5, -1])

In [6]:
A1 = np.load('A1.npy')
A2 = np.load('A2.npy')
A3 = np.load('A3.npy')
A4 = np.load('A4.npy')
A5 = np.load('A5.npy')
A6 = np.load('A6.npy')
A7 = np.load('A7.npy')
A8 = np.load('A8.npy')
A9 = np.load('A9.npy')
A10 = np.load('A10.npy')
A11 = np.load('A11.npy')
A12 = np.load('A12.npy')

display(A9)

array([ 3,  5, -1])