In [2]:
import numpy as np

In [3]:
def f(x):
    return x * np.sin(3*x) - np.exp(x)

def df(x):
    return np.sin(3*x) + 3*x*np.cos(3*x) - np.exp(x)

In [33]:
x = np.array([-1.6])
for i in range(1000):
    x = np.append(x, x [i] - f(x[i]) / df(x[i]))
    fc = f(x[i+1])

    if abs(fc) < 1e-6 :
        break

display(x)
display(i)
display(x[i])
display(fc)

np.save('A1.npy', x)

array([-1.6       ,  3.19799514,  2.46440244,  1.2035359 ,  0.65020146,
       -0.11692334, -0.66052349, -0.52192654, -0.56655274, -0.57074658,
       -0.57078962])

9

np.float64(-0.5707465821813341)

np.float64(-6.016180886803113e-09)

In [27]:
xl = -0.7
xr = -0.4
xcstore = np.array([])
for j in range(0,1000):
    xc = (xl + xr) / 2
    fc = f(xc)
    if fc > 0 :
        xl = xc
    else :
        xr = xc

    xcstore = np.append(xcstore, xc)
    if abs(fc) < 1e-6 :
        break
    

display(xcstore)
display(j)
display(xc)
display(fc)

np.save('A2.npy', xcstore)
np.save('A3.npy', [i,j])

array([-0.55      , -0.625     , -0.5875    , -0.56875   , -0.578125  ,
       -0.5734375 , -0.57109375, -0.56992188, -0.57050781, -0.57080078,
       -0.5706543 , -0.57072754, -0.57076416, -0.57078247, -0.57079163,
       -0.57078705, -0.57078934])

16

-0.5707893371582031

np.float64(-3.747433618972451e-07)

In [32]:
a1 = np.load('A1.npy')
a2 = np.load('A2.npy')
a3 = np.load('A3.npy')

display(a1)
display(a2)
display(a3)

array([-1.6       ,  3.19799514,  2.46440244,  1.2035359 ,  0.65020146,
       -0.11692334, -0.66052349, -0.52192654, -0.56655274, -0.57074658,
       -0.57078962])

array([-0.55      , -0.625     , -0.5875    , -0.56875   , -0.578125  ,
       -0.5734375 , -0.57109375, -0.56992188, -0.57050781, -0.57080078,
       -0.5706543 , -0.57072754, -0.57076416, -0.57078247, -0.57079163,
       -0.57078705, -0.57078934])

array([ 9, 16])